version: '3.8' #https://docs.docker.com/compose/compose-file/compose-file-v3/
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    environment:
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_DEFAULT_USER: rabbitmq-service
      RABBITMQ_DEFAULT_PASS: rabbitmq-service
    container_name: rabbitmq
    restart: always # unless-stopped
    ports:
      - 1883:1883 # mqtt
      - 5672:5672 # broker
      - 15675:15675 # web mqtt
      - 15670:15670 # web mqtt example
      - 9001:9001 # web mqtt
      - 15672:15672 # web management ui: localhost:15672
    volumes:
      - type: bind
        source: ./rabbitmq/config/rabbitmq.conf
        target: /etc/rabbitmq/rabbitmq.conf
        read_only: true
      - type: bind
        source: ./rabbitmq/config/advanced.config
        target: /etc/rabbitmq/advanced.config
        read_only: true
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'check_running']
      interval: 30s
      timeout: 10s
      retries: 3
    command: '/bin/bash -c "rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_web_mqtt rabbitmq_web_mqtt_examples rabbitmq_amqp1_0; rabbitmq-server"'
    networks:
      - broker-network
volumes:
  rabbitmq-data:
networks:
  broker-network:
    driver: bridge
